<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Django on iHADtoinstalllinux</title>
    <link>https://ihadtoinstalllinux.github.io/tags/django/</link>
    <description>Recent content in Django on iHADtoinstalllinux</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Mon, 04 Jul 2022 18:35:02 +0500</lastBuildDate><atom:link href="https://ihadtoinstalllinux.github.io/tags/django/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Уязвимость в web-фреймворке Django, которая может привести к подстановке SQL-кода</title>
      <link>https://ihadtoinstalllinux.github.io/posts/uyazvimost-v-web-freymvorke-django-kotoraya-mozhet-privesti-k-podstanovke-sql-koda-20220704-183502/</link>
      <pubDate>Mon, 04 Jul 2022 18:35:02 +0500</pubDate>
      
      <guid>https://ihadtoinstalllinux.github.io/posts/uyazvimost-v-web-freymvorke-django-kotoraya-mozhet-privesti-k-podstanovke-sql-koda-20220704-183502/</guid>
      <description>Опубликованы корректирующие выпуски web-фреймворка Django 4.0.6 и 3.2.14, в которых устранена уязвимость (CVE-2022-34265), потенциально позволяющая выполнить подстановку своего SQL-кода. Проблема затрагивает приложения, использующие непроверенные внешние данные в параметрах kind и lookup_name, передаваемых в функции Trunc(kind) и Extract(lookup_name). Программы, которые допускают в значениях lookup_name и kind только проверенные данные уязвимость не затрагивает.
https://www.opennet.ru/opennews/art.shtml?num=57452</description>
    </item>
    
  </channel>
</rss>
